services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    networks:
      - mongo-network

  backend:
    build: ./backend 
    restart: always
    ports:
      - "2999:2999" 
    environment:
      DB_URI: mongodb://admin:password@mongo:27017/prod # Adjust database URI
    depends_on:
      - mongo
    networks:
      - mongo-network

  frontend: # Name of your backend service
    build: ./frontend # Path to your backend's Dockerfile
    restart: always
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - mongo-network

volumes:
  mongo-data:
    driver: local

networks:
  mongo-network:
    driver: bridge
