apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: frontend
        name: frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        imagePullPolicy: Never
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    service: frontend
  ports:
  - name: "http"
    port: 80 
    targetPort: 3000
    nodePort: 31000
